name: Format

on:
  pull_request:
    branches: [ "master" ]
    paths:
      - '**.cs'
      - '.github/workflows/dotnet-format.yml'

jobs:
  run-dotnet-format:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-dotnet@v6
      with:
        global-json-file: global.json
    - name: Restore dependencies
      run: dotnet restore
    - name: Check formatting
      run: dotnet format --verify-no-changes
